import { Product } from "@/types/product";
const shopData: Product[] = [
  {
    title: "Havit HV-G69 USB Gamepad",
    reviews: 15,
    category: "tables & chairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 1,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/tables/beechpine/bp1.jpg",
        "/images/products/tables/beechpine/bp2.jpg",
      ],
      previews: [
        "/images/products/tables/beechpine/bp1.jpg",
        "/images/products/tables/beechpine/bp2.jpg",
      ],
    },
  },
  {
    title: "iPhone 14 Plus , 6/128GB",
    reviews: 5,
    category: "tables & chairs",
    price: 99.0,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    discountedPrice: 99.0,
    id: 2,
    imgs: {
      thumbnails: [
        "/images/products/tables/bohemin/b1.jpeg",
        "/images/products/tables/bohemin/b2.jpeg",
      ],
      previews: [
        "/images/products/tables/bohemin/b1.jpeg",
        "/images/products/tables/bohemin/b2.jpeg",
      ],
    },
  },
  {
    title: "Apple iMac M1 24-inch 2021",
    reviews: 5,
    category: "tables & chairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 3,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/tables/forest/f1.jpg",
        "/images/products/tables/forest/f2.jpg",
        "/images/products/tables/forest/f3.jpg",
      ],
      previews: [
        "/images/products/tables/forest/f1.jpg",
        "/images/products/tables/forest/f2.jpg",
        "/images/products/tables/forest/f3.jpg",
      ],
    },
  },
  {
    title: "MacBook Air M1 chip, 8/256GB",
    reviews: 6,
    category: "tables & chairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 4,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/tables/helal/h1.jpeg",
        "/images/products/tables/helal/h2.jpg",
      ],
      previews: [
        "/images/products/tables/helal/h1.jpeg",
        "/images/products/tables/helal/h2.jpg",
      ],
    },
  },
  {
    title: "Apple Watch Ultra",
    reviews: 3,
    category: "tables & chairs",
    price: 99.0,
    discountedPrice: 29.0,
    id: 5,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/tables/modern/m1.jpeg",
      ],
      previews: [
        "/images/products/tables/modern/m1.jpeg",
      ],
    },
  },
  {
    title: "Logitech MX Master 3 Mouse",
    reviews: 15,
    category: "pergola",
    price: 59.0,
    discountedPrice: 29.0,
    id: 6,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/pergola/pergolav1/p1.jpeg",
        "/images/products/pergola/pergolav1/p2.jpeg",
        "/images/products/pergola/pergolav1/p3.jpeg",
      ],
      previews: [
        "/images/products/pergola/pergolav1/p1.jpeg",
        "/images/products/pergola/pergolav1/p2.jpeg",
        "/images/products/pergola/pergolav1/p3.jpeg",
      ],
    },
  },
  {
    title: "Apple iPad Air 5th Gen - 64GB",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 7,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/aro/a1.jpeg",
        "/images/products/storage/aro/a2.jpeg",
      ],
      previews: [
        "/images/products/storage/aro/a1.jpeg",
        "/images/products/storage/aro/a2.jpeg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 8,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/arog/a1.jpeg",
        "/images/products/storage/arog/a2.jpeg",
      ],
      previews: [
        "/images/products/storage/arog/a1.jpeg",
        "/images/products/storage/arog/a2.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 9,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/rustic/r1.png",
        "/images/products/storage/rustic/r2.png",
      ],
      previews: [
        "/images/products/storage/rustic/r1.png",
        "/images/products/storage/rustic/r2.png",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 10,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/steelwithwood/sw1.jpeg",
        "/images/products/storage/steelwithwood/sw2.jpeg",
      ],
      previews: [
        "/images/products/storage/steelwithwood/sw1.jpeg",
        "/images/products/storage/steelwithwood/sw2.jpeg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 11,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/weardroparo/wda1.jpg",
        "/images/products/storage/weardroparo/wda2.jpg",
      ],
      previews: [
        "/images/products/storage/weardroparo/wda1.jpg",
        "/images/products/storage/weardroparo/wda2.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 12,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/m1.jpg",
      ],
      previews: [
        "/images/products/storage/m1.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 13,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/m2.jpeg",
      ],
      previews: [
        "/images/products/storage/m2.jpeg",
      ],
    },
  },
{
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 14,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/m3.jpg",
      ],
      previews: [
        "/images/products/storage/m3.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 15,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/smooth/sd1.jpeg",
      ],
      previews: [
        "/images/products/storage/smooth/sd1.jpeg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 16,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/smooth/sd2.png",
      ],
      previews: [
        "/images/products/storage/smooth/sd2.png",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 17,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/smooth/sd3.jpg",
      ],
      previews: [
        "/images/products/storage/smooth/sd3.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "storage furniture",
    price: 59.0,
    discountedPrice: 29.0,
    id: 18,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/storage/smooth/sd4.jpg",
      ],
      previews: [
        "/images/products/storage/smooth/sd4.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 19,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/bed2lshap/s1.jpeg",
        "/images/products/sofas/bed2lshap/s2.jpeg",
        "/images/products/sofas/bed2lshap/s3.jpeg",
        "/images/products/sofas/bed2lshap/s4.jpeg",
      ],
      previews: [
        "/images/products/sofas/bed2lshap/s1.jpeg",
        "/images/products/sofas/bed2lshap/s2.jpeg",
        "/images/products/sofas/bed2lshap/s3.jpeg",
        "/images/products/sofas/bed2lshap/s4.jpeg",
      ],
    },
  },
      {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 20,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/bedlshap/s1.jpeg",
        "/images/products/sofas/bedlshap/s2.jpeg",
      ],
      previews: [
        "/images/products/sofas/bedlshap/s1.jpeg",
        "/images/products/sofas/bedlshap/s2.jpeg",
      ],
    },
  },
        {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 21,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/boho/b1.jpeg",
        "/images/products/sofas/boho/b2.jpeg",
      ],
      previews: [
        "/images/products/sofas/boho/b1.jpeg",
        "/images/products/sofas/boho/b2.jpeg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 22,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/arabic/a1.jpg",
        "/images/products/sofas/arabic/a2.jpg",
      ],
      previews: [
        "/images/products/sofas/arabic/a1.jpg",
        "/images/products/sofas/arabic/a2.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 23,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/islamic/i1.png",
        "/images/products/sofas/islamic/i2.png",
        "/images/products/sofas/islamic/i3.png",
        "/images/products/sofas/islamic/i4.png",
        "/images/products/sofas/islamic/i5.png",
      ],
      previews: [
        "/images/products/sofas/islamic/i1.png",
        "/images/products/sofas/islamic/i2.png",
        "/images/products/sofas/islamic/i3.png",
        "/images/products/sofas/islamic/i4.png",
        "/images/products/sofas/islamic/i5.png",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 24,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/modern/m1.jpeg",
        "/images/products/sofas/modern/m2.jpeg",
        "/images/products/sofas/modern/m3.jpeg",
        "/images/products/sofas/modern/m4.jpeg",
      ],
      previews: [
        "/images/products/sofas/modern/m1.jpeg",
        "/images/products/sofas/modern/m2.jpeg",
        "/images/products/sofas/modern/m3.jpeg",
        "/images/products/sofas/modern/m4.jpeg",
      ],
    },
  },
      {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 25,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/pandasofaset/p1.jpeg",
        "/images/products/sofas/pandasofaset/p2.jpeg",
        "/images/products/sofas/pandasofaset/p3.jpeg",
        "/images/products/sofas/pandasofaset/p4.jpeg",
      ],
      previews: [
        "/images/products/sofas/pandasofaset/p1.jpeg",
        "/images/products/sofas/pandasofaset/p2.jpeg",
        "/images/products/sofas/pandasofaset/p3.jpeg",
        "/images/products/sofas/pandasofaset/p4.jpeg",
      ],
    },
  },
        {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "sofas & armchairs",
    price: 59.0,
    discountedPrice: 29.0,
    id: 26,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/sofas/r2/r1.jpg",
        "/images/products/sofas/r2/r2.jpg",
      ],
      previews: [
        "/images/products/sofas/r2/r1.jpg",
        "/images/products/sofas/r2/r2.jpg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "Shopverse",
    price: 59.0,
    discountedPrice: 29.0,
    id: 27,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/Shopverse/pallet/p1.jpg",
        "/images/products/Shopverse/pallet/p2.jpg",
        "/images/products/Shopverse/pallet/p3.jpg",
      ],
      previews: [
        "/images/products/Shopverse/pallet/p1.jpg",
        "/images/products/Shopverse/pallet/p2.jpg",
        "/images/products/Shopverse/pallet/p3.jpg",
      ],
    },
  },
            {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "Shopverse",
    price: 59.0,
    discountedPrice: 29.0,
    id: 28,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/Shopverse/pallet2/p1.jpg",
        "/images/products/Shopverse/pallet2/p2.jpg",
      ],
      previews: [
        "/images/products/Shopverse/pallet2/p1.jpg",
        "/images/products/Shopverse/pallet2/p2.jpg",
      ],
    },
  },
            {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "Shopverse",
    price: 59.0,
    discountedPrice: 29.0,
    id: 29,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/Shopverse/pallet3.jpg",
      ],
      previews: [
        "/images/products/Shopverse/pallet3.jpg",
      ],
    },
  },
              {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "Shopverse",
    price: 59.0,
    discountedPrice: 29.0,
    id: 30,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/Shopverse/pallet4.jpg",
      ],
      previews: [
        "/images/products/Shopverse/pallet4.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "Shopverse",
    price: 59.0,
    discountedPrice: 29.0,
    id: 31,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/Shopverse/pallet5.jpg",
      ],
      previews: [
        "/images/products/Shopverse/pallet5.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 32,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom/b1.jpeg",
        "/images/products/bedrooms/bedroom/b2.jpeg",
        "/images/products/bedrooms/bedroom/b3.jpeg",
        "/images/products/bedrooms/bedroom/b4.jpeg",
        "/images/products/bedrooms/bedroom/b5.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom/b1.jpeg",
        "/images/products/bedrooms/bedroom/b2.jpeg",
        "/images/products/bedrooms/bedroom/b3.jpeg",
        "/images/products/bedrooms/bedroom/b4.jpeg",
        "/images/products/bedrooms/bedroom/b5.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 33,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom1/b1.jpeg",
        "/images/products/bedrooms/bedroom1/b2.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom1/b1.jpeg",
        "/images/products/bedrooms/bedroom1/b2.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 34,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom2/b1.jpg",
        "/images/products/bedrooms/bedroom2/b2.jpg",
        "/images/products/bedrooms/bedroom2/b3.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom2/b1.jpg",
        "/images/products/bedrooms/bedroom2/b2.jpg",
        "/images/products/bedrooms/bedroom2/b3.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 35,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom3/b1.jpeg",
        "/images/products/bedrooms/bedroom3/b2.jpeg",
        "/images/products/bedrooms/bedroom3/b3.jpeg",
        "/images/products/bedrooms/bedroom3/b4.jpeg",
        "/images/products/bedrooms/bedroom3/b5.jpeg",
        "/images/products/bedrooms/bedroom3/b6.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom3/b1.jpeg",
        "/images/products/bedrooms/bedroom3/b2.jpeg",
        "/images/products/bedrooms/bedroom3/b3.jpeg",
        "/images/products/bedrooms/bedroom3/b4.jpeg",
        "/images/products/bedrooms/bedroom3/b5.jpeg",
        "/images/products/bedrooms/bedroom3/b6.jpeg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 36,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom4/b1.jpeg",
        "/images/products/bedrooms/bedroom4/b2.jpeg",
        "/images/products/bedrooms/bedroom4/b3.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom4/b1.jpeg",
        "/images/products/bedrooms/bedroom4/b2.jpeg",
        "/images/products/bedrooms/bedroom4/b3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 37,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom5/b1.jpeg",
        "/images/products/bedrooms/bedroom5/b2.jpeg",
        "/images/products/bedrooms/bedroom5/b3.jpeg",
        "/images/products/bedrooms/bedroom5/b4.jpeg",
        "/images/products/bedrooms/bedroom5/b5.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom5/b1.jpeg",
        "/images/products/bedrooms/bedroom5/b2.jpeg",
        "/images/products/bedrooms/bedroom5/b3.jpeg",
        "/images/products/bedrooms/bedroom5/b4.jpeg",
        "/images/products/bedrooms/bedroom5/b5.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 38,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom6/b1.jpg",
        "/images/products/bedrooms/bedroom6/b2.jpeg",
        "/images/products/bedrooms/bedroom6/b3.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom6/b1.jpg",
        "/images/products/bedrooms/bedroom6/b2.jpeg",
        "/images/products/bedrooms/bedroom6/b3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 39,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom7/b1.png",
        "/images/products/bedrooms/bedroom7/b2.png",
        "/images/products/bedrooms/bedroom7/b3.png",
      ],
      previews: [
        "/images/products/bedrooms/bedroom7/b1.png",
        "/images/products/bedrooms/bedroom7/b2.png",
        "/images/products/bedrooms/bedroom7/b3.png",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 40,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom8/b1.jpeg",
        "/images/products/bedrooms/bedroom8/b2.jpeg",
        "/images/products/bedrooms/bedroom8/b3.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom8/b1.jpeg",
        "/images/products/bedrooms/bedroom8/b2.jpeg",
        "/images/products/bedrooms/bedroom8/b3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 41,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom9/b1.jpg",
        "/images/products/bedrooms/bedroom9/b2.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom9/b1.jpg",
        "/images/products/bedrooms/bedroom9/b2.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 42,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom10/b1.jpeg",
        "/images/products/bedrooms/bedroom10/b2.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom10/b1.jpeg",
        "/images/products/bedrooms/bedroom10/b2.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 43,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom11/b1.jpg",
        "/images/products/bedrooms/bedroom11/b2.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom11/b1.jpg",
        "/images/products/bedrooms/bedroom11/b2.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 44,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom12/b1.jpeg",
        "/images/products/bedrooms/bedroom12/b2.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom12/b1.jpeg",
        "/images/products/bedrooms/bedroom12/b2.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 45,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom13/b1.jpg",
        "/images/products/bedrooms/bedroom13/b2.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom13/b1.jpg",
        "/images/products/bedrooms/bedroom13/b2.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 46,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom14/b1.jpg",
        "/images/products/bedrooms/bedroom14/b2.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom14/b1.jpg",
        "/images/products/bedrooms/bedroom14/b2.jpg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 47,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom15.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom15.jpg",
      ],
    },
  },
      {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 48,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom16.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom16.jpg",
      ],
    },
  },
        {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 49,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom17.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom17.jpeg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 50,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom18.jpeg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom18.jpeg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 51,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom19.jpe",
      ],
      previews: [
        "/images/products/bedrooms/bedroom19.jpg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 52,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom20.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom20.jpg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "beds & mattresses",
    price: 59.0,
    discountedPrice: 29.0,
    id: 53,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/bedrooms/bedroom21.jpg",
      ],
      previews: [
        "/images/products/bedrooms/bedroom21.jpg",
      ],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 54,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen/k1.jpeg",
        "/images/products/kitchens/kitchen/k2.jpeg",
        "/images/products/kitchens/kitchen/k3.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen/k1.jpeg",
        "/images/products/kitchens/kitchen/k2.jpeg",
        "/images/products/kitchens/kitchen/k3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 55,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen1/k1.jpeg",
        "/images/products/kitchens/kitchen1/k2.jpeg",
        "/images/products/kitchens/kitchen1/k3.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen1/k1.jpeg",
        "/images/products/kitchens/kitchen1/k2.jpeg",
        "/images/products/kitchens/kitchen1/k3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 56,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen2/k1.jpeg",
        "/images/products/kitchens/kitchen2/k2.jpeg",
        "/images/products/kitchens/kitchen2/k3.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen2/k1.jpeg",
        "/images/products/kitchens/kitchen2/k2.jpeg",
        "/images/products/kitchens/kitchen2/k3.jpeg",
      ],
    },
  },
    {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 57,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen3/k1.jpeg",
        "/images/products/kitchens/kitchen3/k2.jpeg",
        "/images/products/kitchens/kitchen3/k3.jpeg",
        "/images/products/kitchens/kitchen3/k4.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen3/k1.jpeg",
        "/images/products/kitchens/kitchen3/k2.jpeg",
        "/images/products/kitchens/kitchen3/k3.jpeg",
        "/images/products/kitchens/kitchen3/k4.jpeg",
      ],
    },
  },
      {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 58,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen4/k1.jpeg",
        "/images/products/kitchens/kitchen4/k2.jpeg",
        "/images/products/kitchens/kitchen4/k3.jpeg",
        "/images/products/kitchens/kitchen4/k4.jpeg",
        "/images/products/kitchens/kitchen4/k5.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen4/k1.jpeg",
        "/images/products/kitchens/kitchen4/k2.jpeg",
        "/images/products/kitchens/kitchen4/k3.jpeg",
        "/images/products/kitchens/kitchen4/k4.jpeg",
        "/images/products/kitchens/kitchen4/k5.jpeg",
      ],
    },
  },
        {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 59,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen5/k1.jpg",
        "/images/products/kitchens/kitchen5/k2.jpg",
      ],
      previews: [
        "/images/products/kitchens/kitchen5/k1.jpg",
        "/images/products/kitchens/kitchen5/k2.jpg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 60,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen6/k1.jpg",
        "/images/products/kitchens/kitchen6/k2.jpg",
      ],
      previews: [
        "/images/products/kitchens/kitchen6/k1.jpg",
        "/images/products/kitchens/kitchen6/k2.jpg",
      ],
    },
  },
          {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    category: "kitchen & appliances",
    price: 59.0,
    discountedPrice: 29.0,
    id: 61,
    color: ["red", "green"],
    woodTypes: ["beech pine","bohemin", "aro"],
    imgs: {
      thumbnails: [
        "/images/products/kitchens/kitchen7/k1.jpeg",
        "/images/products/kitchens/kitchen7/k2.jpeg",
        "/images/products/kitchens/kitchen7/k3.jpeg",
      ],
      previews: [
        "/images/products/kitchens/kitchen7/k1.jpeg",
        "/images/products/kitchens/kitchen7/k2.jpeg",
        "/images/products/kitchens/kitchen7/k3.jpeg",
      ],
    },
  },
];

export default shopData;
